import { TFilters } from "@/lib/types";

export const colors = {
  accent: "#784e40",
  primary: "#dbb4ad",
  secondary: "#ffe3dc",
  tint: '#b48b7d'
} as const;

export const categories: string[] = [
  'politics',
  'sports',
  'business',
  'technology',
  'entertainment',
  'health',
  'science',
  'lifestyle',
  'travel',
  'culture',
  'education',
  'environment',
  'other'
];

export const languageCodes: { [key: string]: string } = {
  Afar: 'aa',
  Amharic: 'am',
  Arabic: 'ar',
  Bengali: 'bn',
  Bosnian: 'bs',
  Bulgarian: 'bg',
  Burmese: 'my',
  Chinese: 'zh',
  Croatian: 'hr',
  Czech: 'cs',
  Danish: 'da',
  Dutch: 'nl',
  English: 'en',
  Estonian: 'et',
  Finnish: 'fi',
  French: 'fr',
  German: 'de',
  Greek: 'el',
  Hebrew: 'he',
  Hindi: 'hi',
  Hungarian: 'hu',
  Icelandic: 'is',
  Indonesian: 'id',
  Italian: 'it',
  Japanese: 'ja',
  Korean: 'ko',
  Lao: 'lo',
  Latvian: 'lv',
  Lithuanian: 'lt',
  Macedonian: 'mk',
  Malay: 'ms',
  Maltese: 'mt',
  Marathi: 'mr',
  Māori: 'mi',
  Nepali: 'ne',
  Norwegian: 'no',
  Persian: 'fa',
  Polish: 'pl',
  Portuguese: 'pt',
  Romanian: 'ro',
  Russian: 'ru',
  Serbian: 'sr',
  Sinhalese: 'si',
  Slovak: 'sk',
  Slovene: 'sl',
  Somali: 'so',
  Spanish: 'es',
  Swedish: 'sv',
  Tajik: 'tg',
  Tamil: 'ta',
  Telugu: 'te',
  Thai: 'th',
  Turkish: 'tr',
  Ukrainian: 'uk',
  Urdu: 'ur',
  Uzbek: 'uz',
  Vietnamese: 'vi',
};

export const countryCodes: { [key: string]: string } = {
  Afghanistan: 'af',
  Albania: 'al',
  Algeria: 'dz',
  'American Samoa': 'as',
  Anguilla: 'ai',
  Argentina: 'ar',
  Australia: 'au',
  Austria: 'at',
  Bahamas: 'bs',
  Bahrain: 'bh',
  Bangladesh: 'bd',
  Barbados: 'bb',
  Belarus: 'by',
  Belgium: 'be',
  Belize: 'bz',
  Benin: 'bj',
  Bermuda: 'bm',
  Bhutan: 'bt',
  'Bosnia and Herzegovina': 'ba',
  'Bouvet Island': 'bv',
  Brazil: 'br',
  'British Indian Ocean Territory': 'io',
  'Brunei Darussalam': 'bn',
  Bulgaria: 'bg',
  'Burkina Faso': 'bf',
  Burundi: 'bi',
  Cambodia: 'kh',
  Cameroon: 'cm',
  Canada: 'ca',
  'Cape Verde': 'cv',
  'Central African Republic': 'cf',
  Chile: 'cl',
  China: 'cn',
  Colombia: 'co',
  Comoros: 'km',
  'Democratic Republic of the Congo': 'cd',
  'Republic of the Congo': 'cg',
  'Costa Rica': 'cr',
  "Cote D'ivoire": 'ci',
  Croatia: 'hr',
  Cuba: 'cu',
  Cyprus: 'cy',
  'Czech Republic': 'cz',
  Czechia: 'cz',
  Denmark: 'dk',
  Djibouti: 'dj',
  'Dominican Republic': 'do',
  Ecuador: 'ec',
  Egypt: 'eg',
  'El Salvador': 'sv',
  Eritrea: 'er',
  Ethiopia: 'et',
  Fiji: 'fj',
  Finland: 'fi',
  France: 'fr',
  'French Guiana': 'gf',
  'French Polynesia': 'pf',
  Gambia: 'gm',
  Germany: 'de',
  Ghana: 'gh',
  Greece: 'gr',
  Guatemala: 'gt',
  Guinea: 'gn',
  Guyana: 'gy',
  Honduras: 'hn',
  'Hong Kong': 'hk',
  Hungary: 'hu',
  Iceland: 'is',
  India: 'in',
  Indonesia: 'id',
  Iran: 'ir',
  Iraq: 'iq',
  Ireland: 'ie',
  Israel: 'il',
  Italy: 'it',
  Japan: 'jp',
  Jordan: 'jo',
  Kazakhstan: 'kz',
  Kenya: 'ke',
  Kuwait: 'kw',
  Laos: 'la',
  Latvia: 'lv',
  Lebanon: 'lb',
  Lesotho: 'ls',
  Liberia: 'lr',
  Liechtenstein: 'li',
  Lithuania: 'lt',
  Luxembourg: 'lu',
  Macedonia: 'mk',
  Madagascar: 'mg',
  Malawi: 'mw',
  Malaysia: 'my',
  Maldives: 'mv',
  Mali: 'ml',
  Malta: 'mt',
  Mauritania: 'mr',
  Mauritius: 'mu',
  Mexico: 'mx',
  Micronesia: 'fm',
  Moldova: 'md',
  Monaco: 'mc',
  Montenegro: 'me',
  Montserrat: 'ms',
  Morocco: 'ma',
  Myanmar: 'mm',
  Namibia: 'na',
  Nepal: 'np',
  Netherlands: 'nl',
  'New Zealand': 'nz',
  Niger: 'ne',
  Nigeria: 'ng',
  'North Korea': 'kp',
  Norway: 'no',
  Oman: 'om',
  Pakistan: 'pk',
  Palestina: 'ps',
  Paraguay: 'py',
  Peru: 'pe',
  Philippines: 'ph',
  Poland: 'pl',
  Portugal: 'pt',
  Qatar: 'qa',
  Romania: 'ro',
  Russia: 'ru',
  Rwanda: 'rw',
  'Saint Kitts and Nevis': 'kn',
  'Saint Vincent and the Grenadines': 'vc',
  'San Marino': 'sm',
  'Saudi Arabia': 'sa',
  Senegal: 'sn',
  Serbia: 'rs',
  Seychelles: 'sc',
  'Sierra Leone': 'sl',
  Singapore: 'sg',
  Slovakia: 'sk',
  Slovenia: 'si',
  'Solomon Islands': 'sb',
  Somalia: 'so',
  'South Africa': 'za',
  'South Korea': 'kr',
  Spain: 'es',
  'Sri Lanka': 'lk',
  Suriname: 'sr',
  Swaziland: 'sz',
  Sweden: 'se',
  Switzerland: 'ch',
  Syria: 'sy',
  Taiwan: 'tw',
  Tajikistan: 'tj',
  Thailand: 'th',
  'Timor-Leste': 'tl',
  Togo: 'tg',
  Tonga: 'to',
  'Trinidad and Tobago': 'tt',
  Turkey: 'tr',
  Tuvalu: 'tv',
  Ukraine: 'ua',
  Uganda: 'ug',
  'United Arab Emirates': 'ae',
  'United Kingdom': 'gb',
  UK: 'gb',
  'United States': 'us',
  USA: 'us',
  Uruguay: 'uy',
  Uzbekistan: 'uz',
  Vanuatu: 'vu',
  Zambia: 'zm',
};

export const INITIAL_FILTERS: TFilters = {
  text: undefined,
  sourceCountry: undefined,
  lang: undefined,
  sentiment: undefined,
  date: undefined,
  newsSource: undefined,
  category: 'sports',
  author: undefined,
  entity: undefined,
  sortDirection: undefined,
  location: undefined
}